# Generated by Django 4.2.12 on 2024-05-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0002_projectmember_alter_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
